### ISSUE TITLE
Incorrect maps showing in GW section

### ISSUE THREAD

**Issue by almontg** [bplmaps/argomaps#17]
The following maps are showing in the "George Washington's Maps" collection without having been tagged as such in the CMS (and are not, in fact, George Washington's Maps!):

- https://www.argomaps.org/maps/commonwealth:z603vg95j/
- https://www.argomaps.org/maps/commonwealth:z603vg816/
- https://www.argomaps.org/maps/commonwealth:x633f8505/
- https://www.argomaps.org/maps/commonwealth:6t053n752/
- https://www.argomaps.org/maps/commonwealth:z603vg82g/

**Comment by diedrick** [comment]
There's a whole new data system that makes this, so when this goes live or staged, we'll have to check that it actually works.

**Comment by almontg** [comment]
The new maps I added to this tag are there now, but the incorrect maps I identified above are still, stubbornly, showing as George Washington's Maps.

**Comment by diedrick** [comment]
Is this fixed now @almontg ?
