### ISSUE TITLE
Not all people articles showing

### ISSUE THREAD

**Issue by almontg** [bplmaps/argomaps#19]
Not all of the "people" for whom we have content in the CMS are showing on https://www.argomaps.org/people/. The following entries are missing (bold indicates that the article does appear on the site, just not linked from the landing page; non-bolded items have header images and blurbs but no full biography and are not linked anywhere)

- Simeon de Witt (images only)
**- Catherine and Elizabeth Haussard (https://www.argomaps.org/people/catherine-and-elizabeth-haussard/)**
**- Pierre Charles L’Enfant (https://www.argomaps.org/people/pierre-charles-l-enfant/)**
- Joseph Frederick Wallet DesBarres (images only)
- John Mitchell (images only)
- Thomas Jeffreys (images only)
- Robert Sayer (images only)
- Jacques-Nicolas Bellin (images only)
- Thomas Kitchin (images only)
- Georges-Louis Le Rouge (images only)
- John Henry Bastide (images only)
- Jean Baptiste Bourguignon d’Anville (images only)
- Osgood Carleton (images only)
- Rigobert Bonne (images only)
- John Reid (images only)
- John Rocque (images only)
- Nicolas Scull II (images only)
- Thomas Hutchins (images only)
- Joshua Fry (images only)
- Bernard Romans (images only)
- Braddock Mead aka John Green (images only)

Additionally, the articles which are not on the landing page (i.e. the Haussard sisters and L'Enfant) have different styling that the ones which are properly linked. 

Not linking to people who do not have full bios makes sense to me, however if we are doing that then we should un-link the page on Charles Morris Sr. and Jr. (https://www.argomaps.org/people/charles-morris-and-charles-morris-jr/) as there is not full bio there and it is linked from the landing page.

**Comment by almontg** [comment]
Oh, additionally the "related maps" scroller on the bottom of these articles (which I love!) does not actually link to the individual maps, and the tray pop up which should appear when clicking "see x maps" in the hub page does not seem to work:
![image](https://user-images.githubusercontent.com/85258517/213782292-8c5e3d0c-fbf2-4319-b617-c2b8b144f00c.png)

**Comment by diedrick** [comment]
@almontg I think the system is showing only people that have a tag at all. So in the CMS:
![image](https://user-images.githubusercontent.com/9010288/215170261-54afa4d2-6287-4533-ab81-e5d7c172c744.png)
Resolves to these:
![image](https://user-images.githubusercontent.com/9010288/215170060-9d5d3f33-1b03-4e68-863b-45f674589f7f.png)

We could create a tag that says 'Other People' or something like that.

As to: "Additionally, the articles which are not on the landing page (i.e. the Haussard sisters and L'Enfant) have different styling that the ones which are properly linked." ...is this a separate issue? Screenshot might help, and putting it in a separate issue if it's not related, as I'm lost on the context.

The See 45 maps issue is resolved in the next PR.

**Comment by diedrick** [comment]
I added an other mapmakers that might solve this: 
![image](https://user-images.githubusercontent.com/9010288/216146862-e36362d7-0efc-433c-82c4-93e0944d49e6.png)

Though you may be describing other issues beyond the main ones, let's review this after the PR goes live.

**Comment by almontg** [comment]
Sorry it took me a bit to get back to this!
The lack of tags I think is the issue when you get into the sidebar navigation on an article; however, that does not seem to be the reason for the Hussard sisters and Pierre L'Enfant not showing up on the landing page. Pics below:

**Landing page. Haussard sisters and L'Enfant do not appear on this page; Charles Morris, who has no article, does.**
![image](https://user-images.githubusercontent.com/85258517/216388668-c4c70241-742b-43f3-9d03-f2b0769bb380.png)

**Sidebar nav; all people with tags, including Haussard sisters and L'Enfant, appear:** 
![image](https://user-images.githubusercontent.com/85258517/216389121-1c63d463-b5cf-4515-82e5-37b7b612dd4c.png)


As for the styling thing, I think I may have simply dreamed that as I no longer see it haha

**Comment by almontg** [comment]
@diedrick the issue I disscuss above is still there, but the other smaller issues have been resolved; I'll close this and make a new issue post specifically about the landing page.
