### ISSUE TITLE
Metadata not loading

### ISSUE THREAD

**Issue by almontg** [bplmaps/argomaps#20]
Just clicked on this map (https://www.argomaps.org/maps/commonwealth:hx11z022g/) and got the following error:
![image](https://user-images.githubusercontent.com/85258517/213782602-6be78b4d-1737-4a28-a92b-4333cd7663e7.png)

This has been happening on many, but not all maps.

**Comment by diedrick** [comment]
Ala - Can you check to see if this is now working with Garrett's latest update?

**Comment by almontg** [comment]
Yep, this looks like it's been resolved!

**Comment by diedrick** [comment]
I don't know if the bottom right looks like this on this issue page for you, but if so, and if you're happy, you can close the issue:
![image](https://user-images.githubusercontent.com/9010288/213794142-d1603cd6-1d3e-4e7c-afa4-18074d540c77.png)

**Comment by almontg** [comment]
Got it!
