### ISSUE TITLE
Incorrrect titles in  features browse

### ISSUE THREAD

**Issue by almontg** [bplmaps/argomaps#22]
When exploring different features, the title appearing in the left hand side of the top bar next to the bubble tags does not change, i.e.:

![image](https://user-images.githubusercontent.com/85258517/213784418-b8b5443d-7de1-4675-8f1d-a17ea1ad9fb7.png)
![image](https://user-images.githubusercontent.com/85258517/213784479-b37475b4-17a8-4751-adae-6ad708d6afb2.png)

**Comment by diedrick** [comment]
Actually they're not suppose to change, but they are supposed to be the subject type, and that'll be fixed on the next PR.

![image](https://user-images.githubusercontent.com/9010288/214472872-31ff1b65-cc13-4f64-a7e3-c6fa2aee1670.png)
