### ISSUE TITLE
OpenLayers should be included as a JS module, not imported in `head`

### ISSUE THREAD

**Issue by garrettdashnelson** [bplmaps/argomaps#26]
OL should also only be loaded on pages where it is in use (currently the frontpage only), and not on other pages. Modularizing should fix this.

**Comment by diedrick** [comment]
There's apparently many ways to achieve this, but none are either working or pleasing. I would assume that 
`npm install ol`
would get the library installed, and then importing via:
`import * as ol from 'ol';`
`import Extent from 'ol/interaction/Extent.js';`
`import Point from 'ol/geom/Point.js';`
`import Polygon from 'ol/geom/Polygon.js';`
But it's manual and causing other issues.

Then in other places we have css and js loading in the script tags locally (from static and plugins), which I could have happen only for the home page.

What's the method you use, and how much of the library would I want to use?

**Comment by garrettdashnelson** [comment]
@diedrick Take a look at the `componentize-ol` branch where I've demonstrated how this should work. Here, I've done the following:

* Moved all concerns related to the front page map into a new `/components/FrontpageMap` component
* Create an `ol.js` plugin which extracts whatever OL modules are needed
* Added `FrontpageMap` as a component of `index.vue`

You'll see here that this map doesn't do anything; it just spins up a blank map with our basemap tiles drawn from the API. However, you should be able to now use this to bring all the map-related code that was previously in `index.vue` over to the new component.

(One sidebar: there seems to be a bit of Tailwind CSS colliding with the OL styling of the `.ol-zoom` class, I can take a look at that.)

If and when you're ready, I can merge that branch into `staging` and you can work from it. Or you can feel free to copy code from that branch as desired.

**Comment by diedrick** [comment]
Thanks @garrettdashnelson  I've used the same methodology and removed the CDN version, which is currently in michael-working along with all the other changes.

**Comment by garrettdashnelson** [comment]
Closed by #46
