### ISSUE TITLE
Overall web performance needs improvement

### ISSUE THREAD

**Issue by garrettdashnelson** [bplmaps/argomaps#31]
This is more of an over-arching issue than any specific code comment, but overall the performance of the site is laggy right now: both anecdotally it feels slow, and it [scores very poorly](https://pagespeed.web.dev/report?url=https%3A%2F%2Fwww.argomaps.org%2F) on Google's PageSpeed evaluation. I don't think we need to chase a specific page score necessarily (I don't find it the most accurate predictor of how performant a page feels) but I still think there are some things we could do to improve performativity, including:

* Moving more images over to IIIF service and implementing some lazy loading behavior
* Componentizing and splitting certain JS imports and including only the modules needed

I am definitely not an expert at web performance tweaks, so I defer to any best practices in this area with which I may not be familiar.

**Comment by diedrick** [comment]
Not perfect, but definitely an improvement:
![image](https://user-images.githubusercontent.com/9010288/217320126-055d3d38-3b7f-41ba-9918-195f155fc925.png)

**Comment by garrettdashnelson** [comment]
Awesome, this is great, and anecdotally the staging site feels much faster, too.
