### ISSUE TITLE
Consider a few other font styles to replace Rockwell

### ISSUE THREAD

**Issue by garrettdashnelson** [bplmaps/argomaps#36]

**Comment by diedrick** [comment]
The purpose of that main headline and H2 type was to bring together the logo type and the rest of the site, so a bridge between the old and modern. But it really needs to be modern, as that helps the maps and site images stand out as the unique thing, and avoids the ye olde b&b feel. And, at the same time, we don't want the thick verticals and thin horizontals, ie a _didone_ type of font, as that falls apart with anything behind it and feels a bit _Tartuffe_. A slab serif is really the best solution here logically.

We have some new options up here now for your perusal:
https://bytestudios.com/show/argo_fonts/

Or, if you've got another you'd like to see, happy to mock it up.

**Comment by garrettdashnelson** [comment]
I'm not _totally_ convinced that a slab serif is the right choice, but I'm willing to be convinced. Of the examples shown here, I like Mokoko by far the best. 

Any chance you'd be willing to mock up [Silva Display](https://fonts.adobe.com/fonts/silva-display#fonts-section) in at least semibold or heavier by comparison?

**Comment by diedrick** [comment]
Silva Display added to show site: https://bytestudios.com/show/argo_fonts/#

**Comment by almontg** [comment]
I, quite frankly, like all of these; I think I agree w/ Garretts initial assessment that Mokoko is my favorite. Silva Display strikes me as a little dull (but perfectly fine).

**Comment by garrettdashnelson** [comment]
Let's go with Mokoko then if it's a consensus pick?

**Comment by diedrick** [comment]
Sounds good, want to remove and add to your font pack, or get a new one, and paste the new script details here?

**Comment by garrettdashnelson** [comment]
I've added Mokoko to the font stack of the existing TypeKit call, and it should be available immediately. I added Mokoko Variable so that it's available across all weights; it can be accessed like:

```
font-family: mokoko-variable
```

Let me know when it's switched over and I'll take Rockwell out of the stack for performance improvement.

**Comment by diedrick** [comment]
Switch and pushed to staging.

**Comment by garrettdashnelson** [comment]
Looks good to me, and I'll take Rockwell out of the font stack.
