### ISSUE TITLE
Not all people articles showing on landing page

### ISSUE THREAD

**Issue by almontg** [bplmaps/argomaps#37]
The Hussard sisters and Pierre L'Enfant articles are still not showing up on the landing page. Pics below:

**Landing page. Haussard sisters and L'Enfant do not appear on this page; Charles Morris, who has no article, does.**
![image](https://user-images.githubusercontent.com/85258517/216388668-c4c70241-742b-43f3-9d03-f2b0769bb380.png)

**Sidebar nav; all people with tags, including Haussard sisters and L'Enfant, appear:** 
![image](https://user-images.githubusercontent.com/85258517/216389121-1c63d463-b5cf-4515-82e5-37b7b612dd4c.png)

**Comment by diedrick** [comment]
I'm seeing Haussard sisters on Visual Makers and Cool and Unusual, and L'Enfant in Visual Makers. 
https://argo-staging.netlify.app/people/

Though maybe I'm not understanding the issue?

**Comment by almontg** [comment]
Ok this one's on me — I literally *just now* realized that the main landing page is also controlled by tags at the top (face palm).

I think it should default to "all," which would probably be best answered by just adding an "all" tag? If you agree I'm happy to manage that from the CMS.

**Comment by diedrick** [comment]
That would break the rule we have and make this different than every other page with filters, ie. there's not an 'all features' or all 'nations and empires'.

**Comment by almontg** [comment]
My justification for this is that the people articles are a different kind of content than the other filters, since they're articles rather than a list of maps. At least when I click on "people," I expect to see all available people, rather than starting out filtered.

**Comment by diedrick** [comment]
Okay, how about this then:
https://argo-staging.netlify.app/people/

**Comment by almontg** [comment]
Perfect. Thank you!
