### ISSUE TITLE
Add map creator and date to large thumbnails

### ISSUE THREAD

**Issue by almontg** [bplmaps/argomaps#39]
![image](https://user-images.githubusercontent.com/85258517/216663025-c105963b-8776-40ec-9adf-4703beefe675.png)

**Comment by almontg** [comment]
Weirdly, I'm only seeing this in some places on the site; ie it shows for features and languages:
https://argo-staging.netlify.app/explore/4features-2/
https://argo-staging.netlify.app/explore/3languages-0/

But not Nations & Empires:
https://argo-staging.netlify.app/empires-and-nations/

**Comment by diedrick** [comment]
Try now?

**Comment by almontg** [comment]
I see it now! 

It looks a little busy to me visually but that is a different issue. Closing this.
