### ISSUE TITLE
Footnotes

### ISSUE THREAD

**Issue by almontg** [bplmaps/argomaps#41]
Very willing to accept that this is a me issue, but I can't figure out how to get footnotes to work. I can see the options to create a link to an anchor on the page, but not to actually create the anchor:

![image](https://user-images.githubusercontent.com/85258517/216681229-2832cb18-b3f4-4d06-ad42-ea7b05fc64e3.png)

When I try to do it by hand in the html editor accessed via the "source" button, the anchor disappears after I save:

_before save:_
![image](https://user-images.githubusercontent.com/85258517/216681873-68f7948c-16f0-4ad7-acfe-811f37802bb7.png)

_after save:_
![image](https://user-images.githubusercontent.com/85258517/216681896-443e2c8e-3d2a-4e6a-8606-c6f474c1f785.png)

Very open to other ways of handling footnotes, but we do need some kind of system.

**Comment by diedrick** [comment]
Don't you need an it to be an <a name=...> in the anchor, and not an ID in a <p> tag? Like:

(link)
<a href="#Anchorname">linked text</a>

(target)
<a name="Anchorname">a named anchor</a>

**Comment by almontg** [comment]
That also causes the same problem described above—the tag disappears after saving.

**Comment by diedrick** [comment]
Where are you trying to save this and it's not saving?

**Comment by diedrick** [comment]
Do you see the anchor here in Notes?
![image](https://user-images.githubusercontent.com/9010288/217301945-c7fea915-fff8-41de-b748-abbc82904352.png)

And in the People Description source above it, do you see this?
![image](https://user-images.githubusercontent.com/9010288/217302338-eed633b3-9b64-43b3-933b-ff85a9c781fe.png)

**Comment by almontg** [comment]
I can see the text "a named anchor" but it appears to no longer be, in fact, a named anchor: 
![image](https://user-images.githubusercontent.com/85258517/217310627-afb770d4-0b97-4f7f-80c0-5eb12db37b59.png)

**Comment by diedrick** [comment]
It's there for me like this:
![image](https://user-images.githubusercontent.com/9010288/217311309-93add6de-cb1e-4a62-9901-3a081c7157ed.png)
And in source:
![image](https://user-images.githubusercontent.com/9010288/217311604-52d79191-503c-444c-b53b-6ec6e1b6c25f.png)

What browser are you using? And does it still show up as just a p after clearing your cache?

**Comment by almontg** [comment]
Clearing the cache worked! I still can't select anchors from the drop down link creating menu in the wysiwyg editor but I can add them in source. Thank you for walking me through this lol.
