### ISSUE TITLE
Image captions

### ISSUE THREAD

**Issue by almontg** [bplmaps/argomaps#42]
As with footnotes, this is something I think I just can't figure out but very well may be in the editor somewhere!

Michael, I think you'd previously told me I could do this via the image properties window, but I don't see this option anywhere

![image](https://user-images.githubusercontent.com/85258517/216682574-79b028d7-d117-4c12-bb55-c7d9431e32af.png)
![image](https://user-images.githubusercontent.com/85258517/216682618-3160c9aa-4700-4cf3-9ae6-1f1e3ed9abeb.png)
![image](https://user-images.githubusercontent.com/85258517/216682661-335c5142-6f74-48f2-9dc1-4bc47b9883da.png)

**Comment by diedrick** [comment]
I've upgraded the image system to our latest version that does have image captions... tell me if this breaks anything else, of course:

![image](https://user-images.githubusercontent.com/9010288/217122194-98f17468-dd1a-4cb2-834f-710b0b930aa1.png)

(Only works on new embeds, though)

**Comment by almontg** [comment]
I'm not seeing it from the dialogues I get when I click this button: 
![image](https://user-images.githubusercontent.com/85258517/217300610-bd28732a-3ffb-4ba7-941c-c362c4c8afb3.png)

Is there a different way I should be adding the images?

**Comment by almontg** [comment]
https://argo.stage.diedrick.com/admin/people.php/1

**Comment by diedrick** [comment]
This is what shows up for me -- I think you just need to clear your cache.
![image](https://user-images.githubusercontent.com/9010288/217310567-5e5b36ea-1b87-4e49-8cf9-ef17a706140a.png)

I use this clear cache plugin since I clear cache all the time, if that helps:
https://chrome.google.com/webstore/detail/clear-cache-shortcut/jnajhcakejgchhbjlchkfmdidgjefleg

**Comment by almontg** [comment]
As with the other issue clearing my cache fixed it! 

How do I add an image URL using this system? I'm only seeing files that are uploaded to the system. I can do it in the source code of course but that won't give me the caption option. Still using https://argo.stage.diedrick.com/admin/people.php/1

Also, worth nothing that clicking on any of the drop downs throws the following error:

![image](https://user-images.githubusercontent.com/85258517/217338398-81d2588a-1ec2-425d-be68-6c0c61ca6e9e.png)
![image](https://user-images.githubusercontent.com/85258517/217338418-0d2f1cd1-d996-435a-a68a-25a8714443b8.png)

**Comment by diedrick** [comment]
Aha, yes, this system isn't meant for offsite images. But you can just add an image and then switch to source and change out its src="..."

Looking into that strange error with the pulldowns.

**Comment by almontg** [comment]
Perfect. Will do that! Do you want me to leave this open for the pulldowns issue?

**Comment by diedrick** [comment]
That should be fixed now, but you'll have to clear your cache I suspect.

**Comment by almontg** [comment]
Yep, works fine now!

I updated all the images in the people articles; using the new image system the layout looks kind of wonky (see screenshot) but I'm not sure if that is just something that looks strange in the wysiwyg or needs to be addressed to make sure we have a good layout for the published pages.

![image](https://user-images.githubusercontent.com/85258517/217559406-44231125-1a69-40af-b8c4-744036d498ab.png)
https://argo.stage.diedrick.com/admin/people.php/4

**Comment by almontg** [comment]
As usual, I have cleared the cache and now the problem is solved. Someday, maybe, I will learn :p
