### ISSUE TITLE
"All maps" in footer needs URL fix

### ISSUE THREAD

**Issue by garrettdashnelson** [bplmaps/argomaps#45]
The "All maps" in the very bottom footer should link to /maps/everything, not /maps

**Comment by diedrick** [comment]
Changed name of page, not link, as /maps/everything doesn't give the proper hierarchy for search engine.

**Comment by garrettdashnelson** [comment]
@almontg & @diedrick if you can close other issues that have been resolved by PR #46 -- as I have done above as an example -- then we'll be able to start clearing the decks of open issues.
