### ISSUE TITLE
CSS caching?

### ISSUE THREAD

**Issue by diedrick** [bplmaps/argomaps#48]
One of the reasons I avoid component-izing CSS is that some of it gets lost when trying to track down something. For example, I've been trying to change the color on this and 1) there's no indication where the CSS file is (see image) and 2) even when I changed it and updated Staging, it still shows up as the old color.

![image](https://user-images.githubusercontent.com/9010288/217333619-e23e2f2b-f11a-42ce-b836-8b0ffd224ea4.png)

My localhost dev version shows the change and line number so that helps find it, but it's showing the live version there:
![image](https://user-images.githubusercontent.com/9010288/217350093-5e60aca6-26d8-4e2c-a142-521abbf40109.png)

Any idea why the staging site feels like not changing it? (Other changes went through fine.)

And does Nuxt have to turn all CSS into embedded no matter the file structure is?

**Comment by garrettdashnelson** [comment]
@diedrick I think this is because you've defined that color (on line 1854 of main.css) as, verbatim:

```
color: #00000088;
```

and my guess is that the CSS parser is treating an 8-digit hex color (which I will confess I have never seen before) as including an alpha value? I don't see how this is related to componentization as that class doesn't seem to be defined on the component (unless I'm missing something).

**Comment by diedrick** [comment]
Alpha values are common in css colors. 

Of course I know it's right in the main.css, but I couldn't see where it was overridden on the live staging site and that's the place where it wasn't working, so I couldn't ascertain why on earth it wouldn't work. 

In this case, I'll use a different kind of color.

(While I'm open to evolving my thoughts on the benefits, my base issue with componentization is that it's adding a layer of technology, is there's always, and I mean _always_, something exactly like this. I'm sure there's a way to do it "smarter", maybe using BEM or another methodology. But when I build something, I'm expecting it to last well after the parsers die or the fashion of that methodology evolves, or we have AI writing all our code. A layer of technology that breaks moments after its first use is a pretty clear indication of the future.)

**Comment by garrettdashnelson** [comment]
The point about the fragility of build chains is absolutely right, as I know from painful experience. However, in this case, I don't see how the issue has anything to do with componentization. In fact, in this case, the build chain is actually _fixing_ an issue: eight digit hex colors are [not an official part of the CSS spec](https://css-tricks.com/8-digit-hex-codes/) and only supported by some browsers. So I think what's happening here is that when you're in a live dev environment, with no CSS post processing happening, your browser is simply ignoring the alpha value of the 8-digit hex color. When the site is built, and goes through CSS postprocessing, the build chain recognizes the 8-digit hex declaration as nonstandard and transpiles it to a proper `rgba()` declaration.

**Comment by diedrick** [comment]
Notes: 

- The article above is 7 years old
- RRGGBBAA is part of the [RFC](https://www.w3.org/TR/css-color-4/#ex-hex8)
- In web dev world few care about RFC, instead relying on browser support, since the RFC can lag
- [We're good](https://caniuse.com/?search=alpha%20hexadecimal) except IE, which most people do not support
- Staging now uses RRGGBB, accessibility now at 100% in lighthouse
- My componentization issue was that Nuxt pushes all the CSS to be inline, which I assumed is an effect; I'm definitely blurring my issues with the stack, sorry about that.
